server: #服务端口
  port: 8082
  servlet:
    context-path: /admin
    session:
      cookie:
        name: OAUTH2SESSION
      timeout: 240m
  connection-timeout: 15000
  tomcat:
    basedir:  /alidata/smoc/apps/temp

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis: #redis配置
    host: 123.57.216.87
    port: 6555
    password: Dj!bm%Mk8DyP
    database: 1
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 5
  servlet:
    multipart:
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小
#**********************************************************
# manpuman oauth2 token参数设置
#**********************************************************
com:
  manpuman:
    cloud:
      oauth2:
        clientId: 176C2F4344C24F399FAE56DEE77B987C  #客户端名称
        clientSecret: DD07521FD58DF5B493A8C6D3F35C3F71F1D49209A79B212466B15AC50EF156390F1EB96599626A02 #客户端密码
        user-name: authSystemUser    #authSystemUser #用户
        password: 049CB2A5480C582E54EBB82683F67410 #密码
      security: #系统信息配置
        system-marking: smoc-admin #系统标识  本系统和授权管理中心配置的系统标识对应
        login-post-path: /security_login #spring security 拦截登录Post path   用户字段userName  密码字段 password  验证码字段 verificationCode
        system-name: smoc运营中心 #系统名称
        company-name: 北京星语互联科技有限公司  #公司名称
        enable-verify-code: false #是否启用验证码
        help-mobile: 联系电话 #帮助电话

      smoc:
        enterprise-file-path: /alidata/smoc/enterprise/
        mobile-file-root-path: /alidata/smoc/message/mobile  #短信手机号文件根目录
        web-url: http://39.107.110.237:8085/service #导出账号信息：自服务平台网址
        message-resource:
          resource-url: http://39.107.110.237/smoc/message/resource #访问资源路径
          resource-file-root-path: /alidata/smoc/message/resource  #资源文件根目录

        intelligence:
          account: AP0681
          password: 679870213340024832lwoSvz
          domain: domain
          server-address: https://tpl-aim.monyun.cn:57123
          view-address: http://localhost:8080
          resource-file-root-path: /alidata/smoc/intelect/resource/  #资源文件根目录

    #**********************************************************
    # 内置tomcat 配置
    #**********************************************************
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

logging:
  config: classpath:logback-spring.xml
  path: /alidata/smoc/smoc-log/smoc-admin-ui-logs
  level:
    root: info

