server:
  port: 10020

spring:
  application:
    name: cloud-grpc-comsumber
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

grpc:
  client:
    smoc-filters-grpc-server:
      # 服务端地址
      address: 'static://127.0.0.1:18092'
      # 是否开启保持连接（长连接）
      enableKeepAlive: true
      # 保持连接时长（默认20s）
      keepAliveTimeout: 20s
      # 没有RPC调用时是否保持连接（默认false，可禁用避免额外消耗CPU）
      keepAliveWithoutCalls: true
      # 客户端负载均衡策略(round_robin（默认）, pick_first)
#      defaultLoadBalancingPolicy: round_robin
      # 通信类型
      # plaintext | plaintext_upgrade | tls
      # 明文通信且http/2 | 明文通信且升级http/1.1为http/2 | 使用TLS（ALPN/NPN）通信
      negotiationType: plaintext
    GLOBAL:
      security:
        client-auth-enabled: false