server: #服务端口
  port: 18090
  servlet:
    context-path: /smoc-identity
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.114.232:8848

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 172.17.114.232
    port: 6379
    password: xz%smoc40#pm
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

com:
  smoc:
    cloud:
      identification:
        configuration:
          appKey: xwRfbS8LIh
          appScrect: 804f7493a6622482b5f03560d3772d1f
          serviceUri: http://api.faceos.com/openapi

logging:
  config: classpath:logback-spring.xml
  path: /smoc/smoc-log/smoc-identity-logs
  level:
    root: info


