server: #服务端口
  port: 18090
  servlet:
    context-path: /smoc-identity
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.65.102:8848

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: r-2zedjdi7xd84ex153o.redis.rds.aliyuncs.com
    port: 6379
    password: xz%smoc40#pm
    database: 1
    timeout: 6000
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: -1
        min-idle: 5

com:
  smoc:
    cloud:
      identification:
        configuration:
          appKey: xwRfbS8LIh
          appScrect: 804f7493a6622482b5f03560d3772d1f
          serviceUri: http://api.faceos.com/openapi

logging:
  config: classpath:logback-spring.xml
  path: /home/smoc/smoc-log/smoc-identity-logs
  level:
    root: info


