server: #服务端口
  port: 18090
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 256
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  servlet:
    context-path: /smoc-identity
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 123.57.216.87
    port: 6555
    password: Dj!bm%Mk8DyP
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

com:
  smoc:
    cloud:
      identification:
        configuration:
          appKey: xwRfbS8LIh
          appScrect: 804f7493a6622482b5f03560d3772d1f
          serviceUri: http://api.faceos.com/openapi

logging:
  config: classpath:logback-spring.xml
  path: E:/log/smoc-log/smoc-auth-logs
  level:
    root: info


