spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      #Global http timeouts.must be specified in milliseconds. must be specified as a java.time.Duration
      httpclient:
        connect-timeout: 15000
        response-timeout: 5s

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 123.57.216.87
    port: 6555
    password: Dj!bm%Mk8DyP
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

logging:
  config: classpath:logback-spring.xml
  path: E:/log/smoc-log/smoc-filters-logs
  level:
    root: info