server: #服务端口
  port: 18081
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
  servlet:
    context-path: /auth
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.171.216:8848
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    open-in-view: true

  # ========================================================================================
  #  datasource hikari pool
  # ========================================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MpmSpringHikariCP
      jdbc-url: jdbc:mysql://rm-2ze57z500ugv7p42g.mysql.rds.aliyuncs.com:3306/smoc_oauth?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: yunsen_smoc
      password: A%dEjB9!h40
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      connection-test-query: select 1 from dual
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 172.22.171.219
    port: 6379
    password: J15mDngG
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

  #**********************************************************
  # 内置tomcat 配置
  #**********************************************************
com:
  manpuman:
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

logging:
  config: classpath:logback-spring.xml
  path: /smoc/smoc-log/smoc-auth-logs
  level:
    root: info


