# ========================================================================================
# spring  JPA
# ========================================================================================
spring:
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: true

  # ========================================================================================
  #  datasource hikari pool
  # ========================================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MpmSpringHikariCP
      jdbc-url: jdbc:mysql://192.168.0.119:3608/meip_oauth?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: yunsen-bill
      password: Q8%yun8*@P#Wvb
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      connection-test-query: select 1 from dual
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 192.168.0.119
    port: 6479
    password: UAJjnvGcOm987ERTd5
    database: 1
    timeout: 10000
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        max-wait: -1
        min-idle: 5

  #**********************************************************
  # 内置tomcat 配置
  #**********************************************************
com:
  manpuman:
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

logging:
  config: classpath:logback-spring.xml
  path: /home/yunsen/meip-log/meip-auth-logs
  level:
    root: info

