server: #服务端口
  port: 18082
  servlet:
    context-path: /smoc
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.114.232:8848
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    open-in-view: true

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 172.17.114.232
    port: 6379
    password: xz%smoc40#pm
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000


  # ========================================================================================
  #  datasource hikari pool
  # ========================================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MpmSpringHikariCP
      jdbc-url: jdbc:mysql://rm-2zefkckgwskwj59yb.mysql.rds.aliyuncs.com:3306/smoc?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: yunsen_smoc
      password: xz%smoc40#pm
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      connection-test-query: select 1 from dual
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

  #**********************************************************
  # 内置tomcat 配置
  #**********************************************************
com:
  manpuman:
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

    cloud:
      smoc:
        message:
          mobile-file-root-path: /share/resourceFile/message/mobile  #短信手机号文件根目录
          mobile-count-limit: 1000 #该批次手机号总量

logging:
  config: classpath:logback-spring.xml
  path: /smoc/smoc-log/smoc-logs
  level:
    root: info


