server: #服务端口
  port: 18082
  servlet:
    context-path: /smoc
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: true

  # ========================================================================================
  #  datasource hikari pool
  # ========================================================================================
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: MpmSpringHikariCP
      jdbc-url: jdbc:mysql://rm-2zergmfbo0d88p44aao.mysql.rds.aliyuncs.com:3306/smoc?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&autoReconnect=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: yunsen_smoc
      password: YUN%smoc9#40
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      connection-test-query: select 1 from dual
      minimum-idle: 10
      maximum-pool-size: 100
      data-source-properties:
        prepStmtCacheSize: 256
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 123.57.216.87
    port: 6555
    password: Dj!bm%Mk8DyP
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

rocketmq:
  name-server: 123.57.216.87:9876
  producer:
    #生产者组名，规定在一个应用里面必须唯一
    group: group-filter
    #消息发送的超时时间，默认为3000ms
    send-message-timeout: 50000
    #消息达到4096字节的时候，消息就会被压缩。默认4096
    compress-message-body-threshold: 4096
    #最大的消息限制 默认为128K
    maxMessageSize: 4096
    #同步消息发送失败重试次数 默认2次
    retry-times-when-send-failed: 5
    #在内部发送失败时是否重试其他代理,这个参数在有多个broker才生效。
    retry-next-server: true
    #异步消息发送失败重试的次数 默认2次
    retry-times-when-send-async-failed: 5

com:
  manpuman:
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

    cloud:
      smoc:
        message:
          mobile-file-root-path: F:/data/message/mobile  #短信手机号文件根目录
          mobile-count-limit: 1000 #该批次手机号总量

logging:
  config: classpath:logback-spring.xml
  path: E:/log/smoc-log/smoc-logs
  level:
    root: info


