server: #服务端口
  port: 18090
  servlet:
    context-path: /identification
  connection-timeout: 15000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

com:
  smoc:
    cloud:
      identification:
        configuration:
          appKey: xwRfbS8LIh
          appScrect: 804f7493a6622482b5f03560d3772d1f
          serviceUri: http://api.faceos.com/openapi

logging:
  config: classpath:logback-spring.xml
  path: E:/log/smoc-log/smoc-auth-logs
  level:
    root: info


