spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.171.216:8848
    gateway:
      #Global http timeouts.must be specified in milliseconds. must be specified as a java.time.Duration
      httpclient:
        connect-timeout: 15000
        response-timeout: 5s

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 172.22.171.220
    port: 6379
    password: J15mDngG
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

  #**********************************************************
  # 内置tomcat 配置
  #**********************************************************

com:
  smoc:
    cloud:
      gateway:
        configuration:
          #网关签名配置
          signature:
            signStyle: md5_HMAC
            aesIv: BINM6krYfGEvGADKq4iTMvBQ6V/3IWFVaqdwhlUBw5Q=
            aesKey: qUhpGjKp3caWMHgDmHoQzbOQP2lGxlzEjJNAwBwO4Q7Pv8XUpoDJUxEyPleyqy67
            md5HmacKey: ad73qUQDMH2HZrYXTfeSqDl3ZjecgW0bDf2h2zs3KaY=
            shaHmacKey: cgN4u8LsehkotaJKunFAsCign3oaCXJoF6wISxAK+ZRRyfAfrZk/d1EcUnaDi/8C
          #智能梦网验证签名
          intelligence:
            account: AP0681
            password: 679870213340024832lwoSvz
            callback-is-sign: true
            domain: 218.25.208.15
logging:
  config: classpath:logback-spring.xml
  path: /smoc/smoc-log/smoc-gateway-logs
  level:
    root: info