spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.171.248:8848
    gateway:
      #Global http timeouts.must be specified in milliseconds. must be specified as a java.time.Duration
      httpclient:
        connect-timeout: 30000
        response-timeout: 30s
        # 线程池类型，除了默认的elastic，还支持fixed和disabled
        # elastic：无限扩展的线程池
        # fixed：固定数量线程池
        # disabled：不使用线程池——只有一个线程
        pool:
          #          type: elastic
          # 最大线程数，只在类型为fixed时有效
          #          max-connections: 16
          # 从线程池获取连接的最大等待时间（毫秒）
          acquire-timeout: 30000
          # 线程空闲多久会被回收（毫秒）
          # max-idle-time: null
          # 线程最大存活时间（毫秒）
          # max-life-time=null
          # 定时检测周期（毫秒），检测哪些线程需要被回收
          # （1）只有空闲的线程会被回收
          # （2）即使未达到max-idle-time，当达到max-life-time时也会被回收
          # eviction-interval: null

  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: 172.22.171.219
    port: 6379
    password: J15mDngG
    database: 1
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000

  #**********************************************************
  # 内置tomcat 配置
  #**********************************************************

com:
  smoc:
    cloud:
      gateway:
        configuration:
          #网关签名配置
          signature:
            signStyle: md5_HMAC
            aesIv: BINM6krYfGEvGADKq4iTMvBQ6V/3IWFVaqdwhlUBw5Q=
            aesKey: qUhpGjKp3caWMHgDmHoQzbOQP2lGxlzEjJNAwBwO4Q7Pv8XUpoDJUxEyPleyqy67
            md5HmacKey: ad73qUQDMH2HZrYXTfeSqDl3ZjecgW0bDf2h2zs3KaY=
            shaHmacKey: cgN4u8LsehkotaJKunFAsCign3oaCXJoF6wISxAK+ZRRyfAfrZk/d1EcUnaDi/8C
          #智能梦网验证签名
          intelligence:
            account: AP0681
            password: 679870213340024832lwoSvz
            callback-is-sign: true
            domain: 218.25.208.15
logging:
  config: classpath:logback-spring.xml
  path: /smoc/smoc-log/smoc-gateway-logs
  level:
    root: info