server: #服务端口
  port: 8081
  servlet:
    context-path: /auth
    session:
      cookie:
        name: OAUTH2SESSION
      timeout: 240m
  connection-timeout: 15000
#**********************************************************
# manpuman oauth2 token参数设置
#**********************************************************
com:
  manpuman:
    cloud:
      oauth2:
        clientId: 176C2F4344C24F399FAE56DEE77B987C  #客户端名称
        clientSecret: DD07521FD58DF5B493A8C6D3F35C3F71F1D49209A79B212466B15AC50EF156390F1EB96599626A02 #客户端密码
        user-name: authSystemUser    #authSystemUser #用户
        password: 049CB2A5480C582E54EBB82683F67410 #密码
      security: #系统信息配置
        system-marking: meip-auth #系统标识  本系统和授权管理中心配置的系统标识对应
        login-post-path: /security_login #spring security 拦截登录Post path   用户字段userName  密码字段 password  验证码字段 verificationCode
        auth-uri: 172.30.236.149:18081 # 备用 授权中心地址，系统启动时 负载找不到host,系统启动后，会自动使用负载的host  注意不加http:// 及后缀
        system-name: 认证、鉴权中心 #系统名称
        company-name: 中国移动通信集团北京有限公司  #公司名称
        ssl: false
        enable-verify-code: true #是否启用验证码
        help-mobile: 联系电话 #帮助电话
    #**********************************************************
    # 内置tomcat 配置
    #**********************************************************
    tomcat:
      connection-timeout: 15000
      acceptor-thread-count: 4
      min-spare-threads: 100
      max-spare-threads: 300
      accept-count: 200
      max-connections: 1000
      max-threads: 500
      protocol: org.apache.coyote.http11.Http11NioProtocol #org.apache.coyote.http11.Http11AprProtocol

meip-auth: #链接授权管理中心，负载配置（其实可以是网关地址）
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule #配置规则 最空闲连接策略
    ConnectTimeout: 2000 #请求连接超时时间
    ReadTimeout: 6000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数 ,192.168.1.149:18081
    listOfServers: 172.30.236.149:18081,172.30.236.153:18081,172.30.236.154:18081

logging:
  config: classpath:logback-spring.xml
  path: /cmsdata/smoc/smoc-log/smoc-auth-ui-logs
  level:
    root: info

spring:
  #**********************************************************
  # Redis
  #**********************************************************
  redis: #redis配置
    host: r-2zegyswwjdbicif2hd.redis.rds.aliyuncs.com
    port: 6379
    password: Tsmoc40#RedistEst
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 5